// GENERATED by scripts/build_cert.py — do not edit. SERVER-ONLY.
// NEVER import this from a route reachable without an authenticated POST submission,
// and NEVER import it into the barmatrix-app (web) bundle.
import type { CertKeys } from "./cert.js";

export const CERT_KEYS: CertKeys = {
  "M1": {
    "pass": {
      "type": "min_correct",
      "n": 9,
      "of": 10
    },
    "capture": "single",
    "remediation_lessons": [
      "lesson-01",
      "lesson-02"
    ],
    "items": [
      {
        "id": "M1-1",
        "key": "NOT-TRUE",
        "explanation": "Backwards/absolute statement of the law — the Ear catches it without facts; a repudiation is retractable until material reliance."
      },
      {
        "id": "M1-2",
        "key": "NOT-RESPONSIVE",
        "explanation": "True in the abstract but a misfit for a power-of-Congress question — Issue-Sense catches it with the facts."
      },
      {
        "id": "M1-3",
        "key": "NOT-TRUE",
        "explanation": "A merchant's signed firm offer needs no consideration — the statement is false on its face."
      },
      {
        "id": "M1-4",
        "key": "NOT-RESPONSIVE",
        "explanation": "True but answers the wrong call — the question is service, not filing."
      },
      {
        "id": "M1-5",
        "key": "NOT-TRUE",
        "explanation": "A care-based defense does not apply to strict liability for a dangerous propensity — false on its face."
      },
      {
        "id": "M1-6",
        "key": "NOT-RESPONSIVE",
        "explanation": "States the testifying-expert rule, wrong for a retained-but-uncalled (consulting) expert."
      },
      {
        "id": "M1-7",
        "key": "NOT-TRUE",
        "explanation": "There is no general vicarious parental liability — overclaim the Ear catches without facts."
      },
      {
        "id": "M1-8",
        "key": "NOT-RESPONSIVE",
        "explanation": "A true doctrine but a misfit — it does not address whether the repudiation was retracted in time."
      },
      {
        "id": "M1-9",
        "key": "NOT-TRUE",
        "explanation": "Zoning is not a title defect — backwards/flat misstatement caught without facts."
      },
      {
        "id": "M1-10",
        "key": "NOT-RESPONSIVE",
        "explanation": "True but wrong element — the suit targets the mother's own conduct, not the child's."
      }
    ]
  },
  "M2": {
    "pass": {
      "type": "min_correct",
      "n": 9,
      "of": 10
    },
    "capture": "single",
    "remediation_lessons": [
      "lesson-04",
      "lesson-05",
      "lesson-06"
    ],
    "items": [
      {
        "id": "M2-1",
        "key": "tiered-absolute",
        "explanation": "An absolute ('always... every conceivable') overstating a tiered/material-risk standard."
      },
      {
        "id": "M2-2",
        "key": "backwards",
        "explanation": "The PER bars prior/contemporaneous terms, not subsequent modifications — the rule run backwards."
      },
      {
        "id": "M2-3",
        "key": "fabricated-rule",
        "explanation": "Invents a Seventh Amendment 'value' test that does not exist."
      },
      {
        "id": "M2-4",
        "key": "contradiction",
        "explanation": "The conclusion (liable) contradicts its own stated reason (no duty)."
      },
      {
        "id": "M2-5",
        "key": "extreme-of-range",
        "explanation": "Pushes 'qualified' to the extreme 'absolute' end of the range."
      },
      {
        "id": "M2-6",
        "key": "flat-misstatement",
        "explanation": "A flat misstatement of SCOTUS's review jurisdiction."
      },
      {
        "id": "M2-7",
        "key": "half-truth",
        "explanation": "Establishes one element (causation of choice) while omitting the contested element (harm)."
      },
      {
        "id": "M2-8",
        "key": "colloquialism",
        "explanation": "A folk-fairness phrasing substituted for a legal standard."
      },
      {
        "id": "M2-9",
        "key": "even-split",
        "explanation": "An invented even-split compromise with no doctrinal basis."
      },
      {
        "id": "M2-10",
        "key": "autonomy-appeal",
        "explanation": "Appeals to ownership autonomy to override the duty owed to entrants."
      }
    ]
  },
  "M3": {
    "pass": {
      "type": "min_correct",
      "n": 8,
      "of": 10
    },
    "capture": "rule_distractor",
    "remediation_lessons": [
      "lesson-03"
    ],
    "items": [
      {
        "id": "M3-1",
        "key_rule": "RULE",
        "key_distractor": "SILENT-MISSTATEMENT",
        "explanation": "A bright-line number — distractors silently misstate the cap; know it or flag."
      },
      {
        "id": "M3-2",
        "key_rule": "STANDARD",
        "key_distractor": "FINGERPRINT",
        "explanation": "A reasonableness standard leaves room to misapply — distractors fingerprint via overclaim/distortion."
      },
      {
        "id": "M3-3",
        "key_rule": "RULE",
        "key_distractor": "SILENT-MISSTATEMENT",
        "explanation": "A bright-line requirement — distractors silently misstate it (e.g. 'minimal diversity suffices')."
      },
      {
        "id": "M3-4",
        "key_rule": "STANDARD",
        "key_distractor": "FINGERPRINT",
        "explanation": "Degree-based standard — distractors fingerprint by overclaim ('any breach excuses')."
      },
      {
        "id": "M3-5",
        "key_rule": "RULE",
        "key_distractor": "SILENT-MISSTATEMENT",
        "explanation": "A bright-line number — distractors silently misstate the window."
      },
      {
        "id": "M3-6",
        "key_rule": "STANDARD",
        "key_distractor": "FINGERPRINT",
        "explanation": "Foreseeability is a standard — distractors fingerprint by distortion."
      },
      {
        "id": "M3-7",
        "key_rule": "RULE",
        "key_distractor": "SILENT-MISSTATEMENT",
        "explanation": "An enumerated bright-line means — distractors silently misstate the predicate."
      },
      {
        "id": "M3-8",
        "key_rule": "STANDARD",
        "key_distractor": "FINGERPRINT",
        "explanation": "An open-textured standard — distractors fingerprint by overclaim ('any insult')."
      },
      {
        "id": "M3-9",
        "key_rule": "RULE",
        "key_distractor": "SILENT-MISSTATEMENT",
        "explanation": "A bright-line scope (certification only) — distractors silently misstate it."
      },
      {
        "id": "M3-10",
        "key_rule": "STANDARD",
        "key_distractor": "FINGERPRINT",
        "explanation": "A fault standard (knowledge/reckless disregard) — distractors fingerprint by overclaim."
      }
    ]
  },
  "M4": {
    "pass": {
      "type": "min_correct",
      "n": 8,
      "of": 10
    },
    "capture": "single",
    "remediation_lessons": [
      "lesson-07",
      "lesson-08"
    ],
    "items": [
      {
        "id": "M4-1",
        "key": "BAIT-DOCTRINE",
        "explanation": "Pulls the testifying-expert rule into a consulting-expert question."
      },
      {
        "id": "M4-2",
        "key": "MISFIT",
        "explanation": "A true doctrine that does not address the retraction question — a misfit."
      },
      {
        "id": "M4-3",
        "key": "WRONG-ELEMENT",
        "explanation": "Proves the child's fault, not the mother's own negligence — wrong element."
      },
      {
        "id": "M4-4",
        "key": "BAIT-DOCTRINE",
        "explanation": "Imports the IIED standard into a negligent (NIED) mishandling case."
      },
      {
        "id": "M4-5",
        "key": "MISFIT",
        "explanation": "Sovereign immunity is a misfit for a scope-of-commerce-power question."
      },
      {
        "id": "M4-6",
        "key": "BAIT-DOCTRINE",
        "explanation": "Uses the relation-back party prong to admit a new claim — bait-doctrine."
      },
      {
        "id": "M4-7",
        "key": "RESPONSIVE",
        "explanation": "Reliance before retraction is the dispositive, on-point answer."
      },
      {
        "id": "M4-8",
        "key": "MISFIT",
        "explanation": "Due-process framing is a misfit for a dormant-commerce / market-participant question."
      },
      {
        "id": "M4-9",
        "key": "WRONG-ELEMENT",
        "explanation": "Establishes nondisclosure but skips the contested harm element."
      },
      {
        "id": "M4-10",
        "key": "RESPONSIVE",
        "explanation": "An undisclosed restrictive covenant makes title unmarketable — on point."
      }
    ]
  },
  "M5": {
    "pass": {
      "type": "min_correct",
      "n": 8,
      "of": 10
    },
    "capture": "axis_survivor",
    "remediation_lessons": [
      "lesson-09",
      "lesson-10"
    ],
    "items": [
      {
        "id": "M5-1",
        "key_axis": "Market participant vs regulator",
        "key_survivor": "A",
        "explanation": "The state is buying/selling (participant), so the dormant-commerce clause doesn't apply."
      },
      {
        "id": "M5-2",
        "key_axis": "Content-based vs content-neutral",
        "key_survivor": "B",
        "explanation": "A subject-matter exemption turns on the message, so the ban is content-based."
      },
      {
        "id": "M5-3",
        "key_axis": "Same vs different occurrence (relation back)",
        "key_survivor": "A",
        "explanation": "Disclosure vs performance are distinct occurrences, so the new claim does not relate back."
      },
      {
        "id": "M5-4",
        "key_axis": "Retractable vs fixed repudiation",
        "key_survivor": "B",
        "explanation": "Material reliance (the substitute purchase) before the retraction fixes the repudiation."
      },
      {
        "id": "M5-5",
        "key_axis": "Independent state ground vs federal ground",
        "key_survivor": "A",
        "explanation": "The judgment rests on an adequate and independent state ground, so SCOTUS declines review."
      },
      {
        "id": "M5-6",
        "key_axis": "Testifying vs consulting expert",
        "key_survivor": "B",
        "explanation": "A retained, non-testifying (consulting) expert is discoverable only on exceptional circumstances."
      },
      {
        "id": "M5-7",
        "key_axis": "Source of the jury right (federal incorporation vs state law)",
        "key_survivor": "B",
        "explanation": "The Seventh Amendment is not incorporated; the jury right here comes from state law."
      },
      {
        "id": "M5-8",
        "key_axis": "NIED: zone-of-danger vs special exception",
        "key_survivor": "B",
        "explanation": "This is NIED (negligent corpse mishandling), not IIED — the negligent-failure theory governs."
      },
      {
        "id": "M5-9",
        "key_axis": "Section 1367(a) supplemental vs section 1367(b) carve-out",
        "key_survivor": "B",
        "explanation": "Section 1367(b) bars supplemental jurisdiction over the plaintiff's claim against a non-diverse added defendant — no SMJ."
      },
      {
        "id": "M5-10",
        "key_axis": "Legal vs equitable (jury right)",
        "key_survivor": "B",
        "explanation": "Where legal and equitable claims share issues, the common issues go to the jury first (Beacon Theatres)."
      }
    ]
  },
  "M6": {
    "pass": {
      "type": "min_correct",
      "n": 9,
      "of": 10
    },
    "capture": "single",
    "remediation_lessons": [
      "lesson-09",
      "lesson-13"
    ],
    "items": [
      {
        "id": "M6-1",
        "key": "FORK",
        "explanation": "The deciding occurrence-overlap fact is withheld — a missing-fact fork."
      },
      {
        "id": "M6-2",
        "key": "CLEAN",
        "explanation": "The 3-month cap resolves it cleanly — closed after three months."
      },
      {
        "id": "M6-3",
        "key": "FORK",
        "explanation": "Without the pleaded facts the plausibility call cannot be resolved — missing-fact fork."
      },
      {
        "id": "M6-4",
        "key": "FORK",
        "explanation": "The 'only-X/only-Y' shape with an unstated call is a question-ambiguity fork."
      },
      {
        "id": "M6-5",
        "key": "CLEAN",
        "explanation": "Settled: the Seventh Amendment civil-jury right is not incorporated — clean anchor."
      },
      {
        "id": "M6-6",
        "key": "FORK",
        "explanation": "Entrant status (the deciding fact) is withheld — missing-fact fork."
      },
      {
        "id": "M6-7",
        "key": "FORK",
        "explanation": "Legal-vs-factual impossibility splits by jurisdiction (Jaffe) — a split-doctrine fork."
      },
      {
        "id": "M6-8",
        "key": "CLEAN",
        "explanation": "Settled: 23(f) permits discretionary review of the certification decision — clean anchor."
      },
      {
        "id": "M6-9",
        "key": "FORK",
        "explanation": "Bilateral vs unilateral conspiracy splits by jurisdiction — a split-doctrine fork."
      },
      {
        "id": "M6-10",
        "key": "CLEAN",
        "explanation": "The PER does not bar a subsequent modification — clean."
      }
    ]
  },
  "M7": {
    "pass": {
      "type": "min_correct",
      "n": 8,
      "of": 10
    },
    "capture": "single",
    "remediation_lessons": [
      "lesson-11"
    ],
    "items": [
      {
        "id": "M7-1",
        "key": "BA-4 offered-for-purpose",
        "explanation": "Same evidence in or out depending on the offered purpose (Rule 407)."
      },
      {
        "id": "M7-2",
        "key": "BA-3 procedural-frame",
        "explanation": "Tests sufficiency/posture, not the merits."
      },
      {
        "id": "M7-3",
        "key": "BA-2 violation-vs-remedy",
        "explanation": "Existence of the wrong vs whether suppression follows."
      },
      {
        "id": "M7-4",
        "key": "BA-4 offered-for-purpose",
        "explanation": "Admissibility flips on the purpose (impeachment vs substantive use)."
      },
      {
        "id": "M7-5",
        "key": "BA-1 wrong-frame",
        "explanation": "A true rule from a neighboring property-crime context applied to the wrong facts."
      },
      {
        "id": "M7-6",
        "key": "BA-2 violation-vs-remedy",
        "explanation": "Being within the SOF (existence) vs enforceable anyway via an exception."
      },
      {
        "id": "M7-7",
        "key": "BA-3 procedural-frame",
        "explanation": "Tests the reasonable-jury standard of review, not the merits."
      },
      {
        "id": "M7-8",
        "key": "BA-4 offered-for-purpose",
        "explanation": "Insurance is barred for negligence but open to show bias — purpose-dependent (Rule 411)."
      },
      {
        "id": "M7-9",
        "key": "BA-1 wrong-frame",
        "explanation": "A neighboring-context characterization applied to the wrong frame."
      },
      {
        "id": "M7-10",
        "key": "BA-2 violation-vs-remedy",
        "explanation": "Existence of the violation vs the remedy (still usable to impeach if non-coerced)."
      }
    ]
  },
  "M8": {
    "pass": {
      "type": "min_correct",
      "n": 8,
      "of": 10
    },
    "capture": "single",
    "remediation_lessons": [
      "lesson-12"
    ],
    "items": [
      {
        "id": "M8-1",
        "key": "A",
        "explanation": "Complete diversity plus amount > $75,000 (CIV-01); 'minimal diversity suffices' is the documented trap."
      },
      {
        "id": "M8-2",
        "key": "A",
        "explanation": "Time stated, capped at 3 months, no consideration (CON-01); 'needs consideration' (backwards) and 'a buyer's order is never irrevocable' are documented traps."
      },
      {
        "id": "M8-3",
        "key": "A",
        "explanation": "Certification decision only (CIV-06); 'certification and the merits' is the documented trap."
      },
      {
        "id": "M8-4",
        "key": "A",
        "explanation": "Acceptance is effective on dispatch (CON-03); 'on receipt' stated as a flat rule is the documented trap."
      },
      {
        "id": "M8-5",
        "key": "A",
        "explanation": "No physical-harm requirement for corpse mishandling (TOR-06 / TP-16); the 'no recovery without physical harm' and IIED 'extreme and outrageous' answers are the documented traps."
      },
      {
        "id": "M8-6",
        "key": "threshold > merits",
        "explanation": "Standing is a threshold question that disposes before the merits."
      },
      {
        "id": "M8-7",
        "key": "layer-fundamentalness",
        "explanation": "Formation is a more fundamental layer than performance/breach."
      },
      {
        "id": "M8-8",
        "key": "default-tier > heightened",
        "explanation": "Absent a suspect-class/fundamental-right trigger, default to rational basis."
      },
      {
        "id": "M8-9",
        "key": "hedged > absolute",
        "explanation": "A hedged statement beats an absolute one."
      },
      {
        "id": "M8-10",
        "key": "fact-engaged > abstract",
        "explanation": "A fact-engaged rationale beats an abstract recitation."
      }
    ]
  },
  "M9": {
    "pass": {
      "type": "calibration",
      "band_match_min": 8,
      "of": 10,
      "no_undercalled_cut": true
    },
    "capture": "band",
    "remediation_lessons": [
      "lesson-13"
    ],
    "items": [
      {
        "id": "M9-1",
        "key_band": "HIGH",
        "mechanism": "clean cut",
        "is_clean_or_anchor": true,
        "explanation": "Clean cut to the parent's own negligence — commit HIGH."
      },
      {
        "id": "M9-2",
        "key_band": "HIGH",
        "mechanism": "anchor",
        "is_clean_or_anchor": true,
        "explanation": "Firm-offer anchor (capped at 3 months) — commit HIGH."
      },
      {
        "id": "M9-3",
        "key_band": "COIN",
        "mechanism": "fork, fact withheld",
        "is_clean_or_anchor": false,
        "explanation": "The deciding occurrence fact is withheld — a coin; flag."
      },
      {
        "id": "M9-4",
        "key_band": "HIGH",
        "mechanism": "clash on a clear fact",
        "is_clean_or_anchor": false,
        "explanation": "A clash resolved on a clear reliance fact — HIGH."
      },
      {
        "id": "M9-5",
        "key_band": "HIGH",
        "mechanism": "anchor",
        "is_clean_or_anchor": true,
        "explanation": "Section 1367(b) anchor — commit HIGH."
      },
      {
        "id": "M9-6",
        "key_band": "COIN",
        "mechanism": "fork, status withheld",
        "is_clean_or_anchor": false,
        "explanation": "Entrant status is withheld — a coin; flag."
      },
      {
        "id": "M9-7",
        "key_band": "MED",
        "mechanism": "single Call heuristic",
        "is_clean_or_anchor": false,
        "explanation": "Resolved by a single Call heuristic on murky facts — MED."
      },
      {
        "id": "M9-8",
        "key_band": "HIGH",
        "mechanism": "anchor",
        "is_clean_or_anchor": true,
        "explanation": "Corpse-NIED anchor — commit HIGH."
      },
      {
        "id": "M9-9",
        "key_band": "COIN",
        "mechanism": "fork, question-ambiguity",
        "is_clean_or_anchor": false,
        "explanation": "Question-ambiguity with the call unstated — a coin; flag."
      },
      {
        "id": "M9-10",
        "key_band": "HIGH",
        "mechanism": "clash on a clear fact",
        "is_clean_or_anchor": false,
        "explanation": "A clash resolved on a clear content-exemption fact — HIGH."
      }
    ]
  },
  "M10": {
    "pass": {
      "type": "integration",
      "accuracy": {
        "n": 6,
        "of": 7
      },
      "phase_min": 8,
      "of": 10
    },
    "capture": "integration",
    "remediation_lessons": [
      "lesson-14"
    ],
    "items": [
      {
        "id": "M10-1",
        "key_answer": "B",
        "key_phase": "CUT",
        "key_band": "HIGH",
        "is_deterministic": true,
        "is_fork": false,
        "explanation": "Firm-offer anchor at the Cut — firm for that month (within the 3-month cap)."
      },
      {
        "id": "M10-2",
        "key_answer": "D",
        "key_phase": "CLASH",
        "key_band": "HIGH",
        "is_deterministic": true,
        "is_fork": false,
        "explanation": "Clash resolved on the reliance fact — relied before retraction."
      },
      {
        "id": "M10-3",
        "key_answer": "C",
        "key_phase": "CUT",
        "key_band": "HIGH",
        "is_deterministic": true,
        "is_fork": false,
        "explanation": "Section 1367(b) anchor at the Cut — dismiss for no complete diversity."
      },
      {
        "id": "M10-4",
        "key_answer": "B",
        "key_phase": "CLASH",
        "key_band": "HIGH",
        "is_deterministic": true,
        "is_fork": false,
        "explanation": "Clash on the participant fact — market participant (DCC doesn't apply)."
      },
      {
        "id": "M10-5",
        "key_answer": "A",
        "key_phase": "CLASH",
        "key_band": "COIN",
        "is_deterministic": false,
        "is_fork": true,
        "explanation": "FORK — the occurrence-overlap fact is withheld; flag and lean per surrounding facts (A on the canonical facts)."
      },
      {
        "id": "M10-6",
        "key_answer": "B",
        "key_phase": "CUT",
        "key_band": "HIGH",
        "is_deterministic": true,
        "is_fork": false,
        "explanation": "Corpse-NIED anchor at the Cut — recovery without physical harm."
      },
      {
        "id": "M10-7",
        "key_answer": "D",
        "key_phase": "CLASH",
        "key_band": "HIGH",
        "is_deterministic": true,
        "is_fork": false,
        "explanation": "Clash on the content-exemption fact — content-based."
      },
      {
        "id": "M10-8",
        "key_answer": "D",
        "key_phase": "CLASH",
        "key_band": "COIN",
        "is_deterministic": false,
        "is_fork": true,
        "explanation": "FORK — entrant status (the deciding fact) is withheld; flag (answer depends on status)."
      },
      {
        "id": "M10-9",
        "key_answer": "C",
        "key_phase": "CUT",
        "key_band": "HIGH",
        "is_deterministic": true,
        "is_fork": false,
        "explanation": "BA-4 — pin the purpose: a subsequent repair is inadmissible to prove negligence, admissible only for control/feasibility if disputed (Rule 407)."
      },
      {
        "id": "M10-10",
        "key_answer": "C",
        "key_phase": "CALL",
        "key_band": "COIN",
        "is_deterministic": false,
        "is_fork": true,
        "explanation": "FORK (split-doctrine) — legal vs factual impossibility splits by jurisdiction (Jaffe); flag, lean modern/MPC (guilty) if forced."
      }
    ]
  }
} as const;
