// GENERATED by scripts/build_cert.py — do not edit. CLIENT-SAFE (no answer keys).
import type { PublicCertContent } from "./cert.js";

export const CERT_CONTENT: PublicCertContent = {
  "title": "C3 Mastery Certification",
  "preview": true,
  "preview_note": "Preview certification — these are fixed sample items drawn from the program's canonical examples to fix the format and the standard. The live mastery exam will draw fresh, unseen, tagged questions from the bank (by mold / axis / architecture) once the bank is tagged, so it measures transfer, not recall.",
  "overall_gate": "All of M1–M8 passed, M9 in-band (band match on >=8/10 with no under-called clean cut), and M10's four conditions met in a single sitting.",
  "competencies": [
    {
      "id": "M1",
      "title": "The Frame (TRUE vs RESPONSIVE)",
      "lesson_refs": [
        "lesson-01",
        "lesson-02"
      ],
      "capture": "single",
      "pass": {
        "type": "min_correct",
        "n": 9,
        "of": 10
      },
      "label_options": [
        "NOT-TRUE",
        "NOT-RESPONSIVE"
      ],
      "items": [
        {
          "id": "M1-1",
          "prompt": "(Repudiation.) \"A repudiation can't be retracted once communicated.\""
        },
        {
          "id": "M1-2",
          "prompt": "(Federal regulation on states.) \"Sovereign immunity bars suit without consent.\""
        },
        {
          "id": "M1-3",
          "prompt": "(Firm offer.) \"The assurance was unsupported by consideration.\""
        },
        {
          "id": "M1-4",
          "prompt": "(Service-failure motion.) \"Filing commenced the action and it was timely.\""
        },
        {
          "id": "M1-5",
          "prompt": "(Escaped wild snake.) \"The escape was caused by a force of nature.\""
        },
        {
          "id": "M1-6",
          "prompt": "(Non-testifying expert.) \"The estate gets full disclosure of the expert's opinions.\""
        },
        {
          "id": "M1-7",
          "prompt": "(Parent of a negligent child.) \"The mother is liable for any harm her child causes.\""
        },
        {
          "id": "M1-8",
          "prompt": "(Repudiation retraction.) \"The buyer's tender was a constructive condition.\""
        },
        {
          "id": "M1-9",
          "prompt": "(Marketable title.) \"Zoning clouds the title.\""
        },
        {
          "id": "M1-10",
          "prompt": "(Suit against the mother.) \"The child was negligent.\""
        }
      ]
    },
    {
      "id": "M2",
      "title": "The Ear (Name the mold)",
      "lesson_refs": [
        "lesson-04",
        "lesson-05",
        "lesson-06"
      ],
      "capture": "single",
      "pass": {
        "type": "min_correct",
        "n": 9,
        "of": 10
      },
      "label_options": [
        "tiered-absolute",
        "fabricated-rule",
        "extreme-of-range",
        "backwards",
        "contradiction",
        "flat-misstatement",
        "half-truth",
        "colloquialism",
        "even-split",
        "autonomy-appeal"
      ],
      "items": [
        {
          "id": "M2-1",
          "prompt": "\"A patient must always be told every conceivable risk.\""
        },
        {
          "id": "M2-2",
          "prompt": "\"The parol evidence rule bars a subsequent modification.\""
        },
        {
          "id": "M2-3",
          "prompt": "\"Injunctive relief has more than de minimis value under the Seventh Amendment.\""
        },
        {
          "id": "M2-4",
          "prompt": "\"Yes, the landowner is liable, because she owed the trespasser no duty.\""
        },
        {
          "id": "M2-5",
          "prompt": "\"A qualified privilege gives absolute immunity from suit.\""
        },
        {
          "id": "M2-6",
          "prompt": "\"SCOTUS may review only state decisions about the constitutionality of federal laws.\""
        },
        {
          "id": "M2-7",
          "prompt": "(no-harm informed consent) \"The patient would have refused had he known.\""
        },
        {
          "id": "M2-8",
          "prompt": "\"No liability, because it's only fair people watch where they're going.\""
        },
        {
          "id": "M2-9",
          "prompt": "\"The loss should be split evenly between buyer and seller.\""
        },
        {
          "id": "M2-10",
          "prompt": "\"She owned the land, so she could keep the dangerous condition if she wished.\""
        }
      ]
    },
    {
      "id": "M3",
      "title": "Standards vs Rules + predict the distractor",
      "lesson_refs": [
        "lesson-03"
      ],
      "capture": "rule_distractor",
      "pass": {
        "type": "min_correct",
        "n": 8,
        "of": 10
      },
      "rule_options": [
        "RULE",
        "STANDARD"
      ],
      "distractor_options": [
        "SILENT-MISSTATEMENT",
        "FINGERPRINT"
      ],
      "items": [
        {
          "id": "M3-1",
          "prompt": "The three-month firm-offer cap."
        },
        {
          "id": "M3-2",
          "prompt": "Reasonableness of a landowner's precautions."
        },
        {
          "id": "M3-3",
          "prompt": "Complete diversity."
        },
        {
          "id": "M3-4",
          "prompt": "Materiality of a breach."
        },
        {
          "id": "M3-5",
          "prompt": "The 90-day service window."
        },
        {
          "id": "M3-6",
          "prompt": "Foreseeability of a rescuer."
        },
        {
          "id": "M3-7",
          "prompt": "Whether a killing was \"by poison.\""
        },
        {
          "id": "M3-8",
          "prompt": "Extreme-and-outrageous conduct (IIED)."
        },
        {
          "id": "M3-9",
          "prompt": "The scope of a Rule 23(f) appeal."
        },
        {
          "id": "M3-10",
          "prompt": "Actual malice."
        }
      ]
    },
    {
      "id": "M4",
      "title": "Issue-Sense (The not-responsive molds)",
      "lesson_refs": [
        "lesson-07",
        "lesson-08"
      ],
      "capture": "single",
      "pass": {
        "type": "min_correct",
        "n": 8,
        "of": 10
      },
      "label_options": [
        "MISFIT",
        "BAIT-DOCTRINE",
        "WRONG-ELEMENT",
        "RESPONSIVE"
      ],
      "items": [
        {
          "id": "M4-1",
          "prompt": "(Non-testifying expert.) \"Full disclosure of qualifications, opinions, and bases.\""
        },
        {
          "id": "M4-2",
          "prompt": "(Repudiation retraction.) \"Tender was a constructive condition.\""
        },
        {
          "id": "M4-3",
          "prompt": "(Suit against the mother.) \"The child was negligent.\""
        },
        {
          "id": "M4-4",
          "prompt": "(Negligent corpse mishandling.) \"The conduct wasn't extreme and outrageous.\""
        },
        {
          "id": "M4-5",
          "prompt": "(Congress's power over states.) \"Sovereign immunity.\""
        },
        {
          "id": "M4-6",
          "prompt": "(Adding a claim by amendment.) \"The defendant knew or should have known but for a mistake.\""
        },
        {
          "id": "M4-7",
          "prompt": "(Repudiation; substitute bought before the retraction.) \"The buyer relied before the retraction.\""
        },
        {
          "id": "M4-8",
          "prompt": "(Dormant commerce; lower local bidder.) \"Irrational, denied due process.\""
        },
        {
          "id": "M4-9",
          "prompt": "(Informed consent, no harm.) \"A material risk was not disclosed.\""
        },
        {
          "id": "M4-10",
          "prompt": "(Marketable title.) \"The covenant renders the title unmarketable.\""
        }
      ]
    },
    {
      "id": "M5",
      "title": "The Clash (Name the axis; pick the survivor)",
      "lesson_refs": [
        "lesson-09",
        "lesson-10"
      ],
      "capture": "axis_survivor",
      "pass": {
        "type": "min_correct",
        "n": 8,
        "of": 10
      },
      "items": [
        {
          "id": "M5-1",
          "prompt": "(State sold a gas field by bid to a lower local bidder.) Survivors: market participant vs discriminated against interstate commerce. Name the axis and pick the survivor.",
          "axis_options": [
            "Market participant vs regulator",
            "Content-based vs content-neutral",
            "Independent state ground vs federal ground",
            "Specific vs general personal jurisdiction"
          ],
          "survivor_options": [
            {
              "letter": "A",
              "text": "market participant"
            },
            {
              "letter": "B",
              "text": "discriminated against interstate commerce"
            }
          ]
        },
        {
          "id": "M5-2",
          "prompt": "(Picketing ban exempting zoning-topic picketing.) Survivors: content-neutral vs content-based. Name the axis and pick the survivor.",
          "axis_options": [
            "Content-based vs content-neutral",
            "Market participant vs regulator",
            "Strict liability vs negligence (products)",
            "Legal vs equitable (jury right)"
          ],
          "survivor_options": [
            {
              "letter": "A",
              "text": "content-neutral"
            },
            {
              "letter": "B",
              "text": "content-based"
            }
          ]
        },
        {
          "id": "M5-3",
          "prompt": "(Disclosure claim, then negligent-performance claim.) Survivors: different occurrence vs relates back. Name the axis and pick the survivor.",
          "axis_options": [
            "Same vs different occurrence (relation back)",
            "Testifying vs consulting expert",
            "Section 1367(a) supplemental vs section 1367(b) carve-out",
            "Material vs minor breach"
          ],
          "survivor_options": [
            {
              "letter": "A",
              "text": "different occurrence"
            },
            {
              "letter": "B",
              "text": "relates back"
            }
          ]
        },
        {
          "id": "M5-4",
          "prompt": "(Repudiation; substitute bought before the retraction.) Survivors: retracted before performance vs relied before retraction. Name the axis and pick the survivor.",
          "axis_options": [
            "Retractable vs fixed repudiation",
            "Material vs minor breach",
            "Assignment of rights vs delegation of duties",
            "Total vs partial integration (parol evidence)"
          ],
          "survivor_options": [
            {
              "letter": "A",
              "text": "retracted before performance"
            },
            {
              "letter": "B",
              "text": "relied before retraction"
            }
          ]
        },
        {
          "id": "M5-5",
          "prompt": "(State law struck on federal and state grounds; SCOTUS petition.) Survivors: independent state ground vs federal interpretation. Name the axis and pick the survivor.",
          "axis_options": [
            "Independent state ground vs federal ground",
            "Market participant vs regulator",
            "Content-based vs content-neutral",
            "Specific vs general personal jurisdiction"
          ],
          "survivor_options": [
            {
              "letter": "A",
              "text": "independent state ground"
            },
            {
              "letter": "B",
              "text": "federal interpretation"
            }
          ]
        },
        {
          "id": "M5-6",
          "prompt": "(Retained-but-uncalled expert.) Survivors: substantial-need + undue-hardship vs exceptional circumstances. Name the axis and pick the survivor.",
          "axis_options": [
            "Testifying vs consulting expert",
            "Same vs different occurrence (relation back)",
            "Section 1367(a) supplemental vs section 1367(b) carve-out",
            "608(b) character-act vs bias"
          ],
          "survivor_options": [
            {
              "letter": "A",
              "text": "substantial-need + undue-hardship"
            },
            {
              "letter": "B",
              "text": "exceptional circumstances"
            }
          ]
        },
        {
          "id": "M5-7",
          "prompt": "(Jury demand in state court; state rules grant juries in contract cases.) Survivors: Seventh Amendment not incorporated vs state law provides. Name the axis and pick the survivor.",
          "axis_options": [
            "Source of the jury right (federal incorporation vs state law)",
            "Legal vs equitable (jury right)",
            "Independent state ground vs federal ground",
            "Material vs minor breach"
          ],
          "survivor_options": [
            {
              "letter": "A",
              "text": "Seventh Amendment not incorporated"
            },
            {
              "letter": "B",
              "text": "state law provides"
            }
          ]
        },
        {
          "id": "M5-8",
          "prompt": "(Negligently mishandled corpse.) Survivors: extreme-and-outrageous vs negligent failure to safeguard. Name the axis and pick the survivor.",
          "axis_options": [
            "NIED: zone-of-danger vs special exception",
            "Strict liability vs negligence (products)",
            "Direct vs vicarious liability",
            "Material vs minor breach"
          ],
          "survivor_options": [
            {
              "letter": "A",
              "text": "extreme-and-outrageous"
            },
            {
              "letter": "B",
              "text": "negligent failure to safeguard"
            }
          ]
        },
        {
          "id": "M5-9",
          "prompt": "(Diversity; plaintiff adds a non-diverse co-defendant.) Survivors: supplemental jurisdiction vs no subject-matter jurisdiction. Name the axis and pick the survivor.",
          "axis_options": [
            "Section 1367(a) supplemental vs section 1367(b) carve-out",
            "Specific vs general personal jurisdiction",
            "Same vs different occurrence (relation back)",
            "Federal question — well-pleaded vs embedded"
          ],
          "survivor_options": [
            {
              "letter": "A",
              "text": "supplemental jurisdiction"
            },
            {
              "letter": "B",
              "text": "no subject-matter jurisdiction"
            }
          ]
        },
        {
          "id": "M5-10",
          "prompt": "(Mixed legal and equitable claims with common issues.) Survivors: no jury vs jury on the common issues. Name the axis and pick the survivor.",
          "axis_options": [
            "Legal vs equitable (jury right)",
            "Source of the jury right (federal incorporation vs state law)",
            "Independent state ground vs federal ground",
            "Material vs minor breach"
          ],
          "survivor_options": [
            {
              "letter": "A",
              "text": "no jury"
            },
            {
              "letter": "B",
              "text": "jury on the common issues"
            }
          ]
        }
      ]
    },
    {
      "id": "M6",
      "title": "Fork & coin recognition",
      "lesson_refs": [
        "lesson-09",
        "lesson-10",
        "lesson-13"
      ],
      "capture": "single",
      "pass": {
        "type": "min_correct",
        "n": 9,
        "of": 10
      },
      "label_options": [
        "CLEAN",
        "FORK"
      ],
      "items": [
        {
          "id": "M6-1",
          "prompt": "Whether a new claim relates back (occurrence overlap unstated)."
        },
        {
          "id": "M6-2",
          "prompt": "Whether a firm offer is still open after four months."
        },
        {
          "id": "M6-3",
          "prompt": "Whether a complaint survives a 12(b)(6) motion."
        },
        {
          "id": "M6-4",
          "prompt": "\"Yes, but only on certification / only the merits / both / neither,\" with the motion type unstated."
        },
        {
          "id": "M6-5",
          "prompt": "Whether the Seventh Amendment is incorporated."
        },
        {
          "id": "M6-6",
          "prompt": "Whether an entrant was owed an invitee's duty (status unstated)."
        },
        {
          "id": "M6-7",
          "prompt": "Receiving goods believed stolen but not in fact stolen (jurisdiction unstated)."
        },
        {
          "id": "M6-8",
          "prompt": "Whether Rule 23(f) permits an interlocutory appeal of certification."
        },
        {
          "id": "M6-9",
          "prompt": "Conspiracy where the only other party feigned agreement (jurisdiction's rule unstated)."
        },
        {
          "id": "M6-10",
          "prompt": "Whether a parol-evidence offer concerns a subsequent modification."
        }
      ]
    },
    {
      "id": "M7",
      "title": "Bait architecture (Name the setup)",
      "lesson_refs": [
        "lesson-11"
      ],
      "capture": "single",
      "pass": {
        "type": "min_correct",
        "n": 8,
        "of": 10
      },
      "label_options": [
        "BA-1 wrong-frame",
        "BA-2 violation-vs-remedy",
        "BA-3 procedural-frame",
        "BA-4 offered-for-purpose"
      ],
      "items": [
        {
          "id": "M7-1",
          "prompt": "A subsequent repair offered \"to prove negligence.\""
        },
        {
          "id": "M7-2",
          "prompt": "On a 12(b)(6), whether the complaint may proceed."
        },
        {
          "id": "M7-3",
          "prompt": "A search violated the Fourth Amendment; is the gun suppressed?"
        },
        {
          "id": "M7-4",
          "prompt": "A prior inconsistent statement offered \"as substantive proof.\""
        },
        {
          "id": "M7-5",
          "prompt": "Larceny vs embezzlement depending on how possession passed."
        },
        {
          "id": "M7-6",
          "prompt": "The contract is within the Statute of Frauds; is it nonetheless enforceable?"
        },
        {
          "id": "M7-7",
          "prompt": "On JMOL, should the motion be granted?"
        },
        {
          "id": "M7-8",
          "prompt": "Liability insurance offered \"to show the witness is biased.\""
        },
        {
          "id": "M7-9",
          "prompt": "A factually impossible vs legally impossible attempt."
        },
        {
          "id": "M7-10",
          "prompt": "A confession violated Miranda; is it usable to impeach?"
        }
      ]
    },
    {
      "id": "M8",
      "title": "The Call (Anchors + heuristics)",
      "lesson_refs": [
        "lesson-12"
      ],
      "capture": "single",
      "pass": {
        "type": "min_correct",
        "n": 8,
        "of": 10
      },
      "label_options": [
        "threshold > merits",
        "layer-fundamentalness",
        "default-tier > heightened",
        "hedged > absolute",
        "fact-engaged > abstract",
        "anchor > inference",
        "specific > general",
        "rule > standard"
      ],
      "items": [
        {
          "id": "M8-1",
          "prompt": "State the requirements for diversity jurisdiction.",
          "options": [
            {
              "letter": "A",
              "text": "Complete diversity (every plaintiff diverse from every defendant) and amount in controversy > $75,000."
            },
            {
              "letter": "B",
              "text": "Minimal diversity suffices."
            },
            {
              "letter": "C",
              "text": "Complete diversity and amount in controversy of at least $75,000."
            },
            {
              "letter": "D",
              "text": "Either complete diversity or an amount over $75,000."
            }
          ]
        },
        {
          "id": "M8-2",
          "prompt": "State how long a merchant's firm offer is irrevocable, and whether it needs consideration.",
          "options": [
            {
              "letter": "A",
              "text": "For the time stated, capped at 3 months, with no consideration needed."
            },
            {
              "letter": "B",
              "text": "Only if supported by consideration."
            },
            {
              "letter": "C",
              "text": "A buyer's order is never irrevocable."
            },
            {
              "letter": "D",
              "text": "For the time stated with no cap, no consideration needed."
            }
          ]
        },
        {
          "id": "M8-3",
          "prompt": "State what a Rule 23(f) appeal may review.",
          "options": [
            {
              "letter": "A",
              "text": "The class-certification decision only."
            },
            {
              "letter": "B",
              "text": "Certification and the merits."
            },
            {
              "letter": "C",
              "text": "The merits of the underlying claims."
            },
            {
              "letter": "D",
              "text": "Any interlocutory order in the case."
            }
          ]
        },
        {
          "id": "M8-4",
          "prompt": "State when a mailed acceptance is effective.",
          "options": [
            {
              "letter": "A",
              "text": "On dispatch (the mailbox rule)."
            },
            {
              "letter": "B",
              "text": "On receipt."
            },
            {
              "letter": "C",
              "text": "When the offeror reads it."
            },
            {
              "letter": "D",
              "text": "On dispatch, but only for option contracts."
            }
          ]
        },
        {
          "id": "M8-5",
          "prompt": "State whether NIED for negligent corpse-mishandling requires physical harm.",
          "options": [
            {
              "letter": "A",
              "text": "No — corpse mishandling is a recognized no-physical-harm exception."
            },
            {
              "letter": "B",
              "text": "No recovery without physical harm."
            },
            {
              "letter": "C",
              "text": "Only if the conduct was extreme and outrageous."
            },
            {
              "letter": "D",
              "text": "Only if the plaintiff was in the zone of danger."
            }
          ]
        },
        {
          "id": "M8-6",
          "prompt": "Tiebreak: \"Dismissed for lack of standing\" vs \"dismissed on the merits.\""
        },
        {
          "id": "M8-7",
          "prompt": "Tiebreak: \"No contract formed\" vs \"the breach was immaterial.\""
        },
        {
          "id": "M8-8",
          "prompt": "Tiebreak: \"Rational basis — upheld\" vs \"strict scrutiny — struck,\" no trigger shown."
        },
        {
          "id": "M8-9",
          "prompt": "Tiebreak: \"Admissible unless unfairly prejudicial\" vs \"always admissible.\""
        },
        {
          "id": "M8-10",
          "prompt": "Tiebreak: the rationale tied to the stem's facts vs the abstract recitation."
        }
      ]
    },
    {
      "id": "M9",
      "title": "Calibration",
      "lesson_refs": [
        "lesson-13"
      ],
      "capture": "band",
      "pass": {
        "type": "calibration",
        "band_match_min": 8,
        "of": 10,
        "no_undercalled_cut": true
      },
      "band_options": [
        "HIGH",
        "MED",
        "COIN"
      ],
      "items": [
        {
          "id": "M9-1",
          "prompt": "(Suit against the mother of a negligent child.)"
        },
        {
          "id": "M9-2",
          "prompt": "(Firm-offer assurance for the year; orders a month later.)"
        },
        {
          "id": "M9-3",
          "prompt": "(Relation back; occurrence overlap unstated.)"
        },
        {
          "id": "M9-4",
          "prompt": "(Repudiation; substitute bought before the retraction.)"
        },
        {
          "id": "M9-5",
          "prompt": "(Diversity; plaintiff adds a non-diverse co-defendant.)"
        },
        {
          "id": "M9-6",
          "prompt": "(Premises liability; entrant's status unstated.)"
        },
        {
          "id": "M9-7",
          "prompt": "(No-contract-formed vs immaterial-breach; facts murky.)"
        },
        {
          "id": "M9-8",
          "prompt": "(Negligently mishandled corpse; no physical harm.)"
        },
        {
          "id": "M9-9",
          "prompt": "(\"Only-X/only-Y/both/neither\" jury set; motion type unstated.)"
        },
        {
          "id": "M9-10",
          "prompt": "(Picketing ban with a zoning-topic exception.)"
        }
      ]
    },
    {
      "id": "M10",
      "title": "Integration (Timed, full workflow)",
      "lesson_refs": [
        "lesson-14"
      ],
      "capture": "integration",
      "pass": {
        "type": "integration",
        "accuracy": {
          "n": 6,
          "of": 7
        },
        "phase_min": 8,
        "of": 10
      },
      "band_options": [
        "HIGH",
        "MED",
        "COIN"
      ],
      "phase_options": [
        "CUT",
        "CLASH",
        "CALL"
      ],
      "items": [
        {
          "id": "M10-1",
          "prompt": "(Firm-offer assurance for the year; orders a month later.) Pick the answer, name the deciding phase, state a confidence band.",
          "options": [
            {
              "letter": "A",
              "text": "PE"
            },
            {
              "letter": "B",
              "text": "firm for that month"
            },
            {
              "letter": "C",
              "text": "no consideration"
            },
            {
              "letter": "D",
              "text": "longer than three months"
            }
          ]
        },
        {
          "id": "M10-2",
          "prompt": "(Repudiation; substitute bought before the retraction.) Pick the answer, name the deciding phase, state a confidence band.",
          "options": [
            {
              "letter": "A",
              "text": "retracted before performance"
            },
            {
              "letter": "B",
              "text": "constructive condition"
            },
            {
              "letter": "C",
              "text": "not retractable once communicated"
            },
            {
              "letter": "D",
              "text": "relied before retraction"
            }
          ]
        },
        {
          "id": "M10-3",
          "prompt": "(Diversity; non-diverse co-defendant added by the plaintiff.) Pick the answer, name the deciding phase, state a confidence band.",
          "options": [
            {
              "letter": "A",
              "text": "supplemental jurisdiction"
            },
            {
              "letter": "B",
              "text": "judicial economy"
            },
            {
              "letter": "C",
              "text": "dismiss — no complete diversity"
            },
            {
              "letter": "D",
              "text": "not the same case/controversy"
            }
          ]
        },
        {
          "id": "M10-4",
          "prompt": "(State sold a gas field by bid to a lower local bidder.) Pick the answer, name the deciding phase, state a confidence band.",
          "options": [
            {
              "letter": "A",
              "text": "compelling interest"
            },
            {
              "letter": "B",
              "text": "market participant"
            },
            {
              "letter": "C",
              "text": "due process"
            },
            {
              "letter": "D",
              "text": "discriminated against commerce"
            }
          ]
        },
        {
          "id": "M10-5",
          "prompt": "(Relation back; occurrence overlap unstated.) Pick the answer, name the deciding phase, state a confidence band — flag if it is a coin.",
          "options": [
            {
              "letter": "A",
              "text": "different occurrence"
            },
            {
              "letter": "B",
              "text": "relates back"
            },
            {
              "letter": "C",
              "text": "change-of-party prong"
            },
            {
              "letter": "D",
              "text": "SOL expired"
            }
          ]
        },
        {
          "id": "M10-6",
          "prompt": "(Negligently mishandled corpse; no physical harm.) Pick the answer, name the deciding phase, state a confidence band.",
          "options": [
            {
              "letter": "A",
              "text": "no recovery without physical harm"
            },
            {
              "letter": "B",
              "text": "recovery — corpse NIED"
            },
            {
              "letter": "C",
              "text": "only if she witnessed it"
            },
            {
              "letter": "D",
              "text": "only on intent"
            }
          ]
        },
        {
          "id": "M10-7",
          "prompt": "(Picketing ban with a zoning-topic exception.) Pick the answer, name the deciding phase, state a confidence band.",
          "options": [
            {
              "letter": "A",
              "text": "content-neutral"
            },
            {
              "letter": "B",
              "text": "regulates conduct"
            },
            {
              "letter": "C",
              "text": "irrational discrimination"
            },
            {
              "letter": "D",
              "text": "content-based"
            }
          ]
        },
        {
          "id": "M10-8",
          "prompt": "(Premises liability; entrant's status unstated.) Pick the answer, name the deciding phase, state a confidence band — flag if it is a coin.",
          "options": [
            {
              "letter": "A",
              "text": "trespasser — no duty"
            },
            {
              "letter": "B",
              "text": "licensee — warn of known dangers"
            },
            {
              "letter": "C",
              "text": "invitee — reasonable care"
            },
            {
              "letter": "D",
              "text": "depends on status"
            }
          ]
        },
        {
          "id": "M10-9",
          "prompt": "(Subsequent repair offered to prove the defendant's negligence.) Pick the answer, name the deciding phase, state a confidence band.",
          "options": [
            {
              "letter": "A",
              "text": "admissible to prove negligence"
            },
            {
              "letter": "B",
              "text": "inadmissible for any purpose"
            },
            {
              "letter": "C",
              "text": "admissible only for control/feasibility if disputed"
            },
            {
              "letter": "D",
              "text": "admissible as an admission"
            }
          ]
        },
        {
          "id": "M10-10",
          "prompt": "(Attempt; non-stolen goods believed stolen; jurisdiction unstated.) Pick the answer, name the deciding phase, state a confidence band — flag if it is a coin.",
          "options": [
            {
              "letter": "A",
              "text": "guilty — factual impossibility is no defense"
            },
            {
              "letter": "B",
              "text": "not guilty — legal impossibility (traditional / Jaffe)"
            },
            {
              "letter": "C",
              "text": "guilty — the MPC/modern rule turns on the defendant's belief"
            },
            {
              "letter": "D",
              "text": "not guilty — withdrawal"
            }
          ]
        }
      ]
    }
  ]
} as const;
