// diagnostic-pool.data.ts — GENERATED by scripts/ingest_diagnostic_pool.py.
// DO NOT EDIT BY HAND. Edit BARMATRIX/engineering/diagnostic-pool/pool.json.

export type DiagnosticPoolRole = "hard_set" | "random" | "bench";

export interface DiagnosticPoolEntry {
  externalId: string;
  subject: string;
  role: DiagnosticPoolRole;
  order: number;
}

export const DIAGNOSTIC_LENGTH = 12;
export const HARD_SET_COUNT = 6;
export const RANDOM_PULL_COUNT = 6;

export const DIAGNOSTIC_POOL: DiagnosticPoolEntry[] = [
  {
    "externalId": "BM-14093-Christian-Erie-RelationBack-v1",
    "subject": "CIVIL_PROCEDURE",
    "role": "hard_set",
    "order": 1
  },
  {
    "externalId": "BM-DIAG-Q111126",
    "subject": "CONSTITUTIONAL_LAW",
    "role": "hard_set",
    "order": 2
  },
  {
    "externalId": "BM-DIAG-Q111121",
    "subject": "CONTRACTS",
    "role": "hard_set",
    "order": 3
  },
  {
    "externalId": "BM-DIAG-Q111127",
    "subject": "TORTS",
    "role": "hard_set",
    "order": 4
  },
  {
    "externalId": "BM-DIAG-Q111122",
    "subject": "EVIDENCE",
    "role": "hard_set",
    "order": 5
  },
  {
    "externalId": "BM-DIAG-Q111123",
    "subject": "CRIMINAL",
    "role": "hard_set",
    "order": 6
  },
  {
    "externalId": "BM-DIAG-Q111112",
    "subject": "CONSTITUTIONAL_LAW",
    "role": "random",
    "order": 0
  },
  {
    "externalId": "BM-DIAG-Q111113",
    "subject": "CIVIL_PROCEDURE",
    "role": "random",
    "order": 0
  },
  {
    "externalId": "BM-DIAG-Q111114",
    "subject": "CIVIL_PROCEDURE",
    "role": "random",
    "order": 0
  },
  {
    "externalId": "BM-DIAG-Q111115",
    "subject": "CONSTITUTIONAL_LAW",
    "role": "random",
    "order": 0
  },
  {
    "externalId": "BM-DIAG-Q111118",
    "subject": "REAL_PROPERTY",
    "role": "random",
    "order": 0
  },
  {
    "externalId": "BM-DIAG-Q111119",
    "subject": "EVIDENCE",
    "role": "bench",
    "order": 0
  },
  {
    "externalId": "BM-DIAG-Q111120",
    "subject": "CONTRACTS",
    "role": "random",
    "order": 0
  },
  {
    "externalId": "BM-DIAG-Q111124",
    "subject": "REAL_PROPERTY",
    "role": "random",
    "order": 0
  },
  {
    "externalId": "BM-DIAG-Q111125",
    "subject": "CONSTITUTIONAL_LAW",
    "role": "random",
    "order": 0
  },
  {
    "externalId": "BM-DIAG-Q111128",
    "subject": "CONSTITUTIONAL_LAW",
    "role": "random",
    "order": 0
  },
  {
    "externalId": "14299_CHRISTIAN_VARIATION_V1",
    "subject": "CONSTITUTIONAL_LAW",
    "role": "random",
    "order": 0
  },
  {
    "externalId": "BM-DIAG-Q111130",
    "subject": "CONSTITUTIONAL_LAW",
    "role": "random",
    "order": 0
  },
  {
    "externalId": "BM-14400-Christian-Contracts-Mistake-v1",
    "subject": "CONTRACTS",
    "role": "bench",
    "order": 0
  },
  {
    "externalId": "BM-DIAG-Q111117",
    "subject": "CONTRACTS",
    "role": "bench",
    "order": 0
  }
];
